implementation of travisci
nzin/sws pull request #5
Opened 2018-01-06 22:16 UTC by foutoucour

2018-01-07 00:23 UTC, foutoucour commented
Faut rajouter travis maintenant :)

2018-01-07 00:25 UTC, foutoucour commented
Et faire la PR  de tes tests :)

2018-01-09 23:38 UTC, nzin commented
ca m'a l'air bon. tu veux que je merge?

2018-01-10 15:20 UTC, foutoucour commented
@nzin il faut rajouter l'integration travis. Meme s'il y a pas de tests encore :)

2018-01-10 15:30 UTC, foutoucour commented
Je crois que tu vas me detester avec la mise en place de `golint` :)

2018-01-10 15:35 UTC, nzin commented
Salut,

le truc c'est que j'utilise systématiquement Visual Code Studio, et il me lint automatiquement.
Si tu mets golint: soit il fait exactement le boulot, soit ca va rentrer en conflit.

2018-01-10 15:36 UTC, nzin commented
bref, je ne vois pas trop l'intérêt

2018-01-10 15:43 UTC, foutoucour commented
je vois. Mais je suis surpris parce golint trouve beaucoup de points a revoir sur le code. Tu as quoi comme setup dans VCS?

2018-01-10 16:58 UTC, nzin commented
Aucune idée, je peux regarder.
mais visual code studio m'a proposé plusieurs plugins et je les ai tous
installé

On Wed, Jan 10, 2018 at 10:43 AM, Jordi Riera <notifications@github.com>
wrote:

> je vois. Mais je suis surpris parce golint trouve beaucoup de points a
> revoir sur le code. Tu as quoi comme setup dans VCS?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nzin/sws/pull/5#issuecomment-356641161>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AAH4keZzq5myPjDCrGpM7B9Kl62iXZx5ks5tJNqggaJpZM4RVdWK>
> .
>

2018-02-14 20:53 UTC, foutoucour commented
je merge? :)

2018-02-14 22:11 UTC, nzin commented
est ce qu'on pourrait closer ce PR et en faire un autre? je vois des redondance avec ce qui a déjà été fait.
genre: `docker-compose run --rm app go test ./...` ou bien le Dockerfile

2018-02-14 22:12 UTC, nzin requested changes
There is already a Dockerfile, this PR isn't redundant?

2018-02-14 22:22 UTC, nzin commented
je me suis trompé, je croyais qu'on était sur dctycoon...

2018-02-14 22:22 UTC, nzin approved these changes
LGTM

2018-02-14 22:22 UTC, merged